### ISSUE TITLE
[Freture request]: Support issue

### ISSUE THREAD

**Issue by s1204IT** [Awayume/github-pr-tasklist-checker#12]
This is a request to respond not only to **Pull requests** but also to **Issues**.

---

For ISSUE_TEMPLATE:
```yml
  - type: checkboxes
    attributes:
      label: TITLE
      options:
        - label: <!-- Choice --> NEEDED CHOICE MESSAGE
          required: true
```

---
For **Issues**, I'd also like additional options to choose what message to send and whether to automatically close it.

```yml
      - name: Check tasklist
        uses: Awayume/github-pr-tasklist-checker@v2
        with:
          issue-close: true
          close-type: not-planned # Close type can only be selected for issues.
          issue-message: |
            The required item is not selected.
            Please check the requirements again before submitting.
```

If you're planning to integrate these into the same repository, I think it's better to use a prefix like this to separate them from Pull requests.
